# /*
#  * Copyright (c) 2022-2024 KCloud-Platform-IoT Author or Authors. All Rights Reserved.
#  * <p>
#  * Licensed under the Apache License, Version 2.0 (the "License");
#  * you may not use this file except in compliance with the License.
#  * You may obtain a copy of the License at
#  * <p>
#  *   http://www.apache.org/licenses/LICENSE-2.0
#  * <p>
#  * Unless required by applicable law or agreed to in writing, software
#  * distributed under the License is distributed on an "AS IS" BASIS,
#  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  * See the License for the specific language governing permissions and
#  * limitations under the License.
#  */
version: '3'
services:
  postgresql:
    image: timescale/timescaledb:latest-pg16
    container_name: postgresql
    # 保持容器在没有守护程序的情况下运行
    tty: true
    restart: always
    privileged: true
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql16/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=laokou123
      - TZ=Asia/Shanghai
    networks:
      - laokou_network
  redis:
    image: redis:7.4.1
    container_name: redis
    # 保持容器在没有守护程序的情况下运行
    tty: true
    restart: always
    privileged: true
    ports:
      - "6379:6379"
    volumes:
      - ./redis7/conf/redis.conf:/etc/redis/redis.conf
      - ./redis7/data:/data
    command: redis-server --appendonly yes --requirepass 'laokou123'
    environment:
      - TZ=Asia/Shanghai
    networks:
      - laokou_network
  rocketmq-namesrv:
    image: apache/rocketmq:5.3.1
    container_name: rocketmq-namesrv
    # 保持容器在没有守护程序的情况下运行
    tty: true
    restart: always
    privileged: true
    ports:
      - "9876:9876"
    command: sh mqnamesrv
    environment:
      - JAVA_OPT_EXT=-server -Xmx256m -Xms256m -Xmn128m
      - TZ=Asia/Shanghai
    networks:
      - laokou_network
  rocketmq-broker:
    image: apache/rocketmq:5.3.1
    container_name: rocketmq-broker
    # 保持容器在没有守护程序的情况下运行
    tty: true
    restart: always
    privileged: true
    ports:
      - "10909:10909"
      - "10911:10911"
      - "10912:10912"
    # 自动创建主题
    command: sh mqbroker -n rocketmq-namesrv:9876 -c /home/rocketmq/conf/broker.conf autoCreateTopicEnable=true
    environment:
      - JAVA_OPT_EXT=-server Xmx256m -Xms256m -Xmn128m
      - TZ=Asia/Shanghai
    volumes:
      - ./rocketmq5/broker/conf/broker.conf:/home/rocketmq/conf/broker.conf
    networks:
      - laokou_network
    depends_on:
      - rocketmq-namesrv
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: elasticsearch
    # 保持容器在没有守护程序的情况下运行
    tty: true
    restart: always
    privileged: true
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elasticsearch8/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch8/data:/usr/share/elasticsearch/data
      - ./elasticsearch8/logs:/usr/share/elasticsearch/logs
      - ./elasticsearch8/plugins:/usr/share/elasticsearch/plugins
      - ./elasticsearch8/config/certs/elastic-certificates.p12:/usr/share/elasticsearch/config/certs/elastic-certificates.p12
    environment:
      - TZ=Asia/Shanghai
      - ES_JAVA_OPTS=-Xmx512m -Xms512m
      - ELASTIC_PASSWORD=laokou123
    networks:
      - laokou_network
    ulimits:
      memlock:
        soft: -1
        hard: -1
  nacos:
    image: registry.cn-shenzhen.aliyuncs.com/koushenhai/laokou-nacos-prod:3.4.0
    container_name: nacos
    # 保持容器在没有守护程序的情况下运行
    tty: true
    restart: always
    privileged: true
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    volumes:
      - ./nacos/logs:/opt
    env_file:
      - env/nacos.env
    networks:
      - laokou_network
    depends_on:
      - postgresql
  gateway:
    image: registry.cn-shenzhen.aliyuncs.com/koushenhai/laokou-gateway-prod:3.4.0
    container_name: gateway
    tty: true
    env_file:
      - env/common.env
      - env/gateway.env
    ports:
      - "5555:5555"
    volumes:
      - ./gateway/logs:/opt
    restart: always
    privileged: true
    networks:
      - laokou_network
    depends_on:
      - nacos
  auth:
    image: registry.cn-shenzhen.aliyuncs.com/koushenhai/laokou-auth-start-prod:3.4.0
    container_name: auth
    tty: true
    env_file:
      - env/common.env
      - env/auth.env
    ports:
      - "1111:1111"
    volumes:
      - ./auth/logs:/opt
    restart: always
    privileged: true
    networks:
      - laokou_network
    depends_on:
      - nacos
      - admin
      - rocketmq-namesrv
      - rocketmq-broker
  admin:
    image: registry.cn-shenzhen.aliyuncs.com/koushenhai/laokou-admin-start-prod:3.4.0
    container_name: admin
    tty: true
    env_file:
      - env/common.env
      - env/admin.env
    ports:
      - "9990:9990"
    volumes:
      - ./admin/logs:/opt
    restart: always
    privileged: true
    networks:
      - laokou_network
    depends_on:
      - nacos
      - elasticsearch
      - rocketmq-namesrv
      - rocketmq-broker
  ui:
    image: registry.cn-shenzhen.aliyuncs.com/koushenhai/ui-prod:3.4.0
    container_name: ui
    # 保持容器在没有守护程序的情况下运行
    tty: true
    restart: always
    privileged: true
    ports:
      - "443:443"
    volumes:
      - ./nginx/logs:/var/log/nginx
    networks:
      - laokou_network
    depends_on:
      - gateway
      - auth
      - admin
  # 控制台 => admin/laokou123456789
  portainer:
   image: portainer/portainer-ce:latest
   container_name: portainer
   # 保持容器在没有守护程序的情况下运行
   tty: true
   restart: always
   privileged: true
   ports:
     - "9010:9000"
   volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - ./portainer/data:/data
   networks:
     - laokou_network
networks:
  laokou_network:
    driver: bridge
