services:
  # rabbitmq-plugins enable rabbitmq_management
  rabbitmq:
    image: rabbitmq:4.0.6-management
    container_name: rabbitmq
    tty: true
    restart: always
    # 节点名 rabbit@rabbitserver，不然会去容器ID
    hostname: rabbitmq
    environment:
      # 默认虚拟机名
      RABBITMQ_DEFAULT_VHOST: /
      # 用户名
      RABBITMQ_DEFAULT_USER: root
      # 密码
      RABBITMQ_DEFAULT_PASS: laokou123
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
      - ./rabbitmq/plugins:/plugins
    networks:
      - laokou_network

networks:
  laokou_network:
    driver: bridge
