server:
  port: 9033
  # 优雅停机
  shutdown: graceful
spring:
  threads:
    virtual:
      # 开启虚拟线程
      enabled: true
  profiles:
    active: @PROFILE-ACTIVE@
  application:
    name: laokou-sample-shardingsphere
  datasource:
    dynamic:
      datasource:
        master:
          url: jdbc:shardingsphere:nacos:application-shardingsphere.yaml
          driver-class-name: org.laokou.common.shardingsphere.config.nacos.NacosShardingSphereDriver
# mybatis-plus
mybatis-plus:
  # 全局处理
  global-config:
    db-config:
      column-format: "\"%s\""
  tenant:
    enabled: false
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl

logging:
  config: classpath:log4j2-@PROFILE-ACTIVE@.xml
