# /*
#  * Copyright (c) 2022-2025 KCloud-Platform-IoT Author or Authors. All Rights Reserved.
#  * <p>
#  * Licensed under the Apache License, Version 2.0 (the "License");
#  * you may not use this file except in compliance with the License.
#  * You may obtain a copy of the License at
#  * <p>
#  *   http://www.apache.org/licenses/LICENSE-2.0
#  * <p>
#  * Unless required by applicable law or agreed to in writing, software
#  * distributed under the License is distributed on an "AS IS" BASIS,
#  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  * See the License for the specific language governing permissions and
#  * limitations under the License.
#  */
services:
  seata:
    image: registry.cn-shenzhen.aliyuncs.com/koushenhai/laokou-sample-seata-server:3.4.2
    container_name: seata
    tty: true
    env_file:
      - env/common.env
      - env/seata.env
    ports:
      - "7091:7091"
      - "8091:8091"
    volumes:
      - ./seata/logs:/opt
    extra_hosts:
      - "postgresql:127.0.0.1"
      - "nacos:127.0.0.1"
      - "redis:127.0.0.1"
    restart: always
    privileged: true
    networks:
      - laokou_network

networks:
  laokou_network:
    driver: bridge
