server:
  port: 9036
  http2:
    enabled: true
  shutdown: graceful

spring:
  application:
    name: laokou-sample-grpc-client
  profiles:
    active: @PROFILE-ACTIVE@
  grpc-client:
    ip: 127.0.0.1
    port: 1114
  lifecycle:
    timeout-per-shutdown-phase: "2m"
  threads:
    virtual:
      enabled: true
logging:
  config: classpath:log4j2-@PROFILE-ACTIVE@.xml
