name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [21]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          architecture: x64
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Gradle Run Build
        run: |
          cd laokou-gradle
          chmod +x gradlew
          ./gradlew build
