name: Java CI with Maven

on:
  push:
    branches: [ "prod_生产分支_仅用于老寇使用_其他人请使用master分支" ]
  pull_request:
    branches: [ "prod_生产分支_仅用于老寇使用_其他人请使用master分支" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [21]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          architecture: x64
      - name: Build with Maven
        run: mvn clean install -P prod -DskipTests -B
      - name: Build the Docker image
        run: |
          # 登录阿里云镜像仓库
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} registry.cn-shenzhen.aliyuncs.com
          # ========== 构建laokou-gateway ==========
          cd /home/runner/work/KCloud-Platform-IoT/KCloud-Platform-IoT/laokou-cloud/laokou-gateway
          # 使用Dockerfile构建镜像
          docker build . --file Dockerfile --tag registry.cn-shenzhen.aliyuncs.com/koushenhai/laokou-gateway-prod:3.4.2
          # 推送镜像到镜像仓库
          docker push registry.cn-shenzhen.aliyuncs.com/koushenhai/laokou-gateway-prod:3.4.2
          # ========== 构建laokou-nacos ==========
          cd /home/runner/work/KCloud-Platform-IoT/KCloud-Platform-IoT/laokou-cloud/laokou-nacos
          # 使用Dockerfile构建镜像
          docker build . --file Dockerfile --tag registry.cn-shenzhen.aliyuncs.com/koushenhai/laokou-nacos-prod:3.4.2
          # 推送镜像到镜像仓库
          docker push registry.cn-shenzhen.aliyuncs.com/koushenhai/laokou-nacos-prod:3.4.2
          # ========== 构建laokou-auth ==========
          cd /home/runner/work/KCloud-Platform-IoT/KCloud-Platform-IoT/laokou-service/laokou-auth/laokou-auth-start
          # 使用Dockerfile构建镜像
          docker build . --file Dockerfile --tag registry.cn-shenzhen.aliyuncs.com/koushenhai/laokou-auth-start-prod:3.4.2
          # 推送镜像到镜像仓库
          docker push registry.cn-shenzhen.aliyuncs.com/koushenhai/laokou-auth-start-prod:3.4.2
          # ========== 构建laokou-admin ==========
          cd /home/runner/work/KCloud-Platform-IoT/KCloud-Platform-IoT/laokou-service/laokou-admin/laokou-admin-start
          # 使用Dockerfile构建镜像
          docker build . --file Dockerfile --tag registry.cn-shenzhen.aliyuncs.com/koushenhai/laokou-admin-start-prod:3.4.2
          # 推送镜像到镜像仓库
          docker push registry.cn-shenzhen.aliyuncs.com/koushenhai/laokou-admin-start-prod:3.4.2
